// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.27.0

package db

type User struct {
	ID              int64
	Email           string
	HashedPassword  string
	Username        *string
	UserImageUri    *string
	CompanyName     *string
	CompanyImageUri *string
}
